---
title: "betaMC: Example Using the SCorMC Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-Cheung-2023
  @Dudgeon-2017
vignette: >
  %\VignetteIndexEntry{betaMC: Example Using the SCorMC Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
semipartial correlation coefficients
are generated using
the `SCorMC()` function from the `betaMC` package.
In this example,
we use the data set and the model used in
[betaMC: Example Using the BetaMC Function](example-beta-mc.html).


``` r
library(betaMC)
```




``` r
df <- betaMC::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Monte Carlo Sampling Distribution of Parameters

#### Normal-Theory Approach


``` r
mvn <- MC(object, type = "mvn")
```

#### Asymptotic distribution-free Approach


``` r
adf <- MC(object, type = "adf")
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- MC(object, type = "hc3")
```

### Semipartial Correlation Coefficients

#### Normal-Theory Approach


``` r
mvn <- SCorMC(mvn)
```

#### Asymptotic distribution-free Approach


``` r
adf <- SCorMC(adf)
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- SCorMC(hc3)
```

## Methods

### summary

Summary of the results of `SCorMC()`.


``` r
summary(mvn)
#> Call:
#> SCorMC(object = mvn)
#> 
#> Semipartial correlations
#> type = "mvn"
#>            est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4312 0.0770 20000 0.1705 0.2285 0.2707 0.5723 0.6244 0.6898
#> PCTGRT  0.3430 0.0744 20000 0.1191 0.1573 0.1949 0.4857 0.5435 0.6031
#> PCTSUPP 0.2385 0.0701 20000 0.0265 0.0644 0.1012 0.3771 0.4287 0.4858
```

``` r
summary(adf)
#> Call:
#> SCorMC(object = adf)
#> 
#> Semipartial correlations
#> type = "adf"
#>            est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4312 0.0707 20000 0.0893 0.2103 0.2706 0.5477 0.5924 0.6456
#> PCTGRT  0.3430 0.0709 20000 0.0766 0.1453 0.1915 0.4688 0.5152 0.5804
#> PCTSUPP 0.2385 0.0697 20000 0.0013 0.0502 0.0951 0.3689 0.4170 0.4716
```

``` r
summary(hc3)
#> Call:
#> SCorMC(object = hc3)
#> 
#> Semipartial correlations
#> type = "hc3"
#>            est     se     R   0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4312 0.0866 20000  0.0487 0.1407 0.2212 0.5669 0.6172 0.6788
#> PCTGRT  0.3430 0.0829 20000  0.0483 0.1056 0.1604 0.4874 0.5404 0.6068
#> PCTSUPP 0.2385 0.0790 20000 -0.0346 0.0246 0.0772 0.3889 0.4472 0.5182
```

### coef

Return the vector of estimates.


``` r
coef(mvn)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4311525 0.3430075 0.2384789
```

``` r
coef(adf)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4311525 0.3430075 0.2384789
```

``` r
coef(hc3)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4311525 0.3430075 0.2384789
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(mvn)
#>                NARTIC        PCTGRT       PCTSUPP
#> NARTIC   0.0059274548 -0.0012167784 -0.0008618646
#> PCTGRT  -0.0012167784  0.0055324560 -0.0008342224
#> PCTSUPP -0.0008618646 -0.0008342224  0.0049195408
```

``` r
vcov(adf)
#>                NARTIC        PCTGRT       PCTSUPP
#> NARTIC   0.0049974108  0.0002634982 -0.0003690405
#> PCTGRT   0.0002634982  0.0050244640 -0.0005948999
#> PCTSUPP -0.0003690405 -0.0005948999  0.0048544551
```

``` r
vcov(hc3)
#>                NARTIC        PCTGRT       PCTSUPP
#> NARTIC   0.0075043369  0.0008426676 -0.0001716679
#> PCTGRT   0.0008426676  0.0068777169 -0.0006003425
#> PCTSUPP -0.0001716679 -0.0006003425  0.0062482399
```

### confint

Return confidence intervals.


``` r
confint(mvn, level = 0.95)
#>             2.5 %    97.5 %
#> NARTIC  0.2706736 0.5723131
#> PCTGRT  0.1948593 0.4857045
#> PCTSUPP 0.1012490 0.3770589
```

``` r
confint(adf, level = 0.95)
#>              2.5 %    97.5 %
#> NARTIC  0.27063965 0.5476799
#> PCTGRT  0.19151714 0.4687909
#> PCTSUPP 0.09507793 0.3688795
```

``` r
confint(hc3, level = 0.95)
#>             2.5 %    97.5 %
#> NARTIC  0.2211816 0.5668765
#> PCTGRT  0.1604257 0.4874132
#> PCTSUPP 0.0771931 0.3889084
```

## References
