---
title: "betaMC: Example Using the PCorMC Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-Cheung-2023
  @Dudgeon-2017
vignette: >
  %\VignetteIndexEntry{betaMC: Example Using the PCorMC Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
squared partial correlation coefficients
are generated using
the `PCorMC()` function from the `betaMC` package.
In this example,
we use the data set and the model used in
[betaMC: Example Using the BetaMC Function](example-beta-mc.html).


``` r
library(betaMC)
```




``` r
df <- betaMC::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Monte Carlo Sampling Distribution of Parameters

#### Normal-Theory Approach


``` r
mvn <- MC(object, type = "mvn")
```

#### Asymptotic distribution-free Approach


``` r
adf <- MC(object, type = "adf")
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- MC(object, type = "hc3")
```

### Squared Partial Correlation Coefficients

#### Normal-Theory Approach


``` r
mvn <- PCorMC(mvn)
```

#### Asymptotic distribution-free Approach


``` r
adf <- PCorMC(adf)
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- PCorMC(hc3)
```

## Methods

### summary

Summary of the results of `PCorMC()`.


``` r
summary(mvn)
#> Call:
#> PCorMC(object = mvn)
#> 
#> Squared partial correlations
#> type = "mvn"
#>            est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4874 0.1053 20000 0.1127 0.1807 0.2430 0.6514 0.7086 0.7763
#> PCTGRT  0.3757 0.1073 20000 0.0500 0.1001 0.1474 0.5618 0.6249 0.7069
#> PCTSUPP 0.2254 0.0993 20000 0.0057 0.0198 0.0468 0.4281 0.5062 0.5782
summary(adf)
#> Call:
#> PCorMC(object = adf)
#> 
#> Squared partial correlations
#> type = "adf"
#>            est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4874 0.0997 20000 0.0381 0.1502 0.2411 0.6329 0.6893 0.7518
#> PCTGRT  0.3757 0.1004 20000 0.0334 0.0880 0.1460 0.5378 0.5936 0.6666
#> PCTSUPP 0.2254 0.1029 20000 0.0005 0.0094 0.0368 0.4335 0.5047 0.5897
summary(hc3)
#> Call:
#> PCorMC(object = hc3)
#> 
#> Squared partial correlations
#> type = "hc3"
#>            est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4874 0.1185 20000 0.0101 0.0747 0.1802 0.6484 0.7076 0.7726
#> PCTGRT  0.3757 0.1152 20000 0.0068 0.0483 0.1071 0.5536 0.6167 0.6846
#> PCTSUPP 0.2254 0.1138 20000 0.0001 0.0034 0.0248 0.4577 0.5465 0.6468
```

### coef

Return the vector of estimates.


``` r
coef(mvn)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4874382 0.3757383 0.2253739
coef(adf)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4874382 0.3757383 0.2253739
coef(hc3)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4874382 0.3757383 0.2253739
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(mvn)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC  0.0110932147 0.0006673043 0.0004004950
#> PCTGRT  0.0006673043 0.0115040181 0.0001156673
#> PCTSUPP 0.0004004950 0.0001156673 0.0098550210
vcov(adf)
#>              NARTIC       PCTGRT      PCTSUPP
#> NARTIC  0.009937808 0.0024649569 0.0020029526
#> PCTGRT  0.002464957 0.0100806860 0.0007876848
#> PCTSUPP 0.002002953 0.0007876848 0.0105864956
vcov(hc3)
#>              NARTIC      PCTGRT     PCTSUPP
#> NARTIC  0.014033927 0.003688422 0.002908552
#> PCTGRT  0.003688422 0.013275149 0.001000406
#> PCTSUPP 0.002908552 0.001000406 0.012951539
```

### confint

Return confidence intervals.


``` r
confint(mvn, level = 0.95)
#>              2.5 %    97.5 %
#> NARTIC  0.24300742 0.6514329
#> PCTGRT  0.14741339 0.5617781
#> PCTSUPP 0.04678045 0.4280831
confint(adf, level = 0.95)
#>              2.5 %    97.5 %
#> NARTIC  0.24105542 0.6329125
#> PCTGRT  0.14596278 0.5377823
#> PCTSUPP 0.03683088 0.4334947
confint(hc3, level = 0.95)
#>              2.5 %    97.5 %
#> NARTIC  0.18024021 0.6484085
#> PCTGRT  0.10707071 0.5536133
#> PCTSUPP 0.02483994 0.4576693
```

## References
