---
title: "betaMC: Example Using the BetaMC Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-Cheung-2023
  @Dudgeon-2017
vignette: >
  %\VignetteIndexEntry{betaMC: Example Using the BetaMC Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



In this example, a multiple regression model is fitted
using program quality ratings (`QUALITY`) as the regressand/outcome variable
and number of published articles attributed to the program faculty members (`NARTIC`),
percent of faculty members holding research grants (`PCTGRT`), and
percentage of program graduates who received support (`PCTSUPP`) as regressor/predictor variables
using a data set from 1982 ratings of 46 doctoral programs in psychology in the USA [@NationalResearchCouncil-1982].
Confidence intervals for the standardized regression coefficients are generated
using the `BetaMC()` function from the `betaMC` package.


``` r
library(betaMC)
```




``` r
df <- betaMC::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Monte Carlo Sampling Distribution of Parameters

#### Normal-Theory Approach


``` r
mvn <- MC(object, type = "mvn")
```

#### Asymptotic distribution-free Approach


``` r
adf <- MC(object, type = "adf")
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- MC(object, type = "hc3")
```

### Standardized Regression Slopes

#### Normal-Theory Approach


``` r
mvn <- BetaMC(mvn)
```

#### Asymptotic distribution-free Approach


``` r
adf <- BetaMC(adf)
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- BetaMC(hc3)
```

## Methods

### summary

Summary of the results of `BetaMC()`.


``` r
summary(mvn)
#> Call:
#> BetaMC(object = mvn)
#> 
#> Standardized regression slopes
#> type = "mvn"
#>            est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4951 0.0762 20000 0.2361 0.2901 0.3370 0.6365 0.6806 0.7274
#> PCTGRT  0.3915 0.0772 20000 0.1331 0.1904 0.2356 0.5387 0.5835 0.6315
#> PCTSUPP 0.2632 0.0750 20000 0.0264 0.0749 0.1180 0.4116 0.4624 0.5287
summary(adf)
#> Call:
#> BetaMC(object = adf)
#> 
#> Standardized regression slopes
#> type = "adf"
#>            est     se     R   0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4951 0.0677 20000  0.2642 0.3118 0.3536 0.6178 0.6602 0.6953
#> PCTGRT  0.3915 0.0709 20000  0.1270 0.1938 0.2414 0.5185 0.5625 0.6165
#> PCTSUPP 0.2632 0.0761 20000 -0.0054 0.0597 0.1071 0.4067 0.4517 0.5068
summary(hc3)
#> Call:
#> BetaMC(object = hc3)
#> 
#> Standardized regression slopes
#> type = "hc3"
#>            est     se     R   0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> NARTIC  0.4951 0.0803 20000  0.2063 0.2693 0.3224 0.6366 0.6821 0.7296
#> PCTGRT  0.3915 0.0831 20000  0.1008 0.1640 0.2157 0.5428 0.5844 0.6438
#> PCTSUPP 0.2632 0.0852 20000 -0.0330 0.0280 0.0884 0.4254 0.4791 0.5423
```

### coef

Return the vector of estimates.


``` r
coef(mvn)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4951451 0.3914887 0.2632477
coef(adf)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4951451 0.3914887 0.2632477
coef(hc3)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4951451 0.3914887 0.2632477
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(mvn)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC   0.005813246 -0.003327552 -0.002189672
#> PCTGRT  -0.003327552  0.005965054 -0.001733688
#> PCTSUPP -0.002189672 -0.001733688  0.005621350
vcov(adf)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC   0.004576798 -0.002530112 -0.001718818
#> PCTGRT  -0.002530112  0.005028938 -0.001803847
#> PCTSUPP -0.001718818 -0.001803847  0.005793617
vcov(hc3)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC   0.006449548 -0.003703344 -0.002000135
#> PCTGRT  -0.003703344  0.006904215 -0.002376650
#> PCTSUPP -0.002000135 -0.002376650  0.007264220
```

### confint

Return confidence intervals.


``` r
confint(mvn, level = 0.95)
#>             2.5 %    97.5 %
#> NARTIC  0.3369847 0.6365108
#> PCTGRT  0.2356129 0.5387022
#> PCTSUPP 0.1179584 0.4115677
confint(adf, level = 0.95)
#>             2.5 %    97.5 %
#> NARTIC  0.3536355 0.6178023
#> PCTGRT  0.2413848 0.5185170
#> PCTSUPP 0.1070826 0.4067120
confint(hc3, level = 0.95)
#>              2.5 %    97.5 %
#> NARTIC  0.32241435 0.6365836
#> PCTGRT  0.21572237 0.5427765
#> PCTSUPP 0.08837824 0.4254480
```

## References
