---
title: "betaMC: Example Using the RSqMC Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-Cheung-2023
  @Dudgeon-2017
vignette: >
  %\VignetteIndexEntry{betaMC: Example Using the RSqMC Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



Confidence intervals for
multiple correlation coefficients
(R-squared and adjusted R-squared)
are generated using
the `RSqMC()` function from the `betaMC` package.
In this example,
we use the data set and the model used in
[betaMC: Example Using the BetaMC Function](example-beta-mc.html).


``` r
library(betaMC)
```




``` r
df <- betaMC::nas1982
```

### Regression

Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

### Monte Carlo Sampling Distribution of Parameters

#### Normal-Theory Approach


``` r
mvn <- MC(object, type = "mvn")
```

#### Asymptotic distribution-free Approach


``` r
adf <- MC(object, type = "adf")
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- MC(object, type = "hc3")
```

### Multiple Correlation Coefficients

#### Normal-Theory Approach


``` r
mvn <- RSqMC(mvn)
```

#### Asymptotic distribution-free Approach


``` r
adf <- RSqMC(adf)
```

#### Heteroskedasticity Consistent Approach (HC3)


``` r
hc3 <- RSqMC(hc3)
```

## Methods

### summary

Summary of the results of `RSqMC()`.


``` r
summary(mvn)
#> Call:
#> RSqMC(object = mvn)
#> 
#> R-squared and adjusted R-squared
#> type = "mvn"
#>        est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> rsq 0.8045 0.0557 20000 0.5187 0.5989 0.6633 0.8801 0.9013 0.9260
#> adj 0.7906 0.0597 20000 0.4843 0.5703 0.6392 0.8715 0.8942 0.9207
summary(adf)
#> Call:
#> RSqMC(object = adf)
#> 
#> R-squared and adjusted R-squared
#> type = "adf"
#>        est     se     R  0.05%   0.5%   2.5%  97.5% 99.5% 99.95%
#> rsq 0.8045 0.0546 20000 0.5430 0.6174 0.6661 0.8797 0.902 0.9217
#> adj 0.7906 0.0585 20000 0.5104 0.5901 0.6423 0.8711 0.895 0.9161
summary(hc3)
#> Call:
#> RSqMC(object = hc3)
#> 
#> R-squared and adjusted R-squared
#> type = "hc3"
#>        est     se     R  0.05%   0.5%   2.5%  97.5%  99.5% 99.95%
#> rsq 0.8045 0.0621 20000 0.4830 0.5818 0.6465 0.8875 0.9101 0.9382
#> adj 0.7906 0.0665 20000 0.4461 0.5520 0.6212 0.8795 0.9037 0.9338
```

### coef

Return the vector of estimates.


``` r
coef(mvn)
#>       rsq       adj 
#> 0.8045263 0.7905638
coef(adf)
#>       rsq       adj 
#> 0.8045263 0.7905638
coef(hc3)
#>       rsq       adj 
#> 0.8045263 0.7905638
```

### vcov

Return the sampling covariance matrix.


``` r
vcov(mvn)
#>             rsq         adj
#> rsq 0.003101585 0.003323127
#> adj 0.003323127 0.003560493
vcov(adf)
#>             rsq         adj
#> rsq 0.002978179 0.003190906
#> adj 0.003190906 0.003418828
vcov(hc3)
#>             rsq         adj
#> rsq 0.003854306 0.004129613
#> adj 0.004129613 0.004424586
```

### confint

Return confidence intervals.


``` r
confint(mvn, level = 0.95)
#>         2.5 %    97.5 %
#> rsq 0.6632873 0.8801023
#> adj 0.6392364 0.8715382
confint(adf, level = 0.95)
#>         2.5 %    97.5 %
#> rsq 0.6661151 0.8796947
#> adj 0.6422662 0.8711015
confint(hc3, level = 0.95)
#>         2.5 %    97.5 %
#> rsq 0.6464990 0.8875356
#> adj 0.6212489 0.8795025
```

## References
